### ISSUE TITLE
TLS Certificate on astralapp.com broken

### ISSUE THREAD

**Issue by Maddosaurus** [astralapp/astral#416] opened 2024-08-03 16:24 UTC
Hey there! 
Looks like https://astralapp.com/ is currently broken as cloudflare is rather unhappy about the certificate.
Any chances of getting the hosted version up and running again?
I really enjoyed using and demoing it on a whim :heart:

**Comment by syropian** [comment] 2024-08-03 17:52
Duplicate of #415

**Comment by syropian** [comment] 2024-08-03 17:53
Should be back up Monday evening or Tuesday morning EST time! Sorry for the inconvenience

**Closed** 2024-08-03 17:52 UTC

**Comment by syropian** [comment] 2024-08-06 13:41
Hello! The site is now back up, thanks for your patience!

**Comment by Maddosaurus** [comment] 2024-08-07 14:10
@syropian Are you sure about that? astralapp.com now runs into Cloudflares' 522 :hourglass:

**Comment by syropian** [comment] 2024-08-07 14:13
The app lives at https://app.astralapp.com and should work fine.

**Comment by Maddosaurus** [comment] 2024-08-07 14:14
Ah yes, thank you very much!
