### ISSUE TITLE
Unable to fetch readme from GitHub

### ISSUE THREAD

**Issue by Ibrahim-Islam** [astralapp/astral#98] opened 2016-10-10 14:59 UTC
This error when there is no Readme.md for a repo and due to this cannot add tags to the repo.

**Comment by alexbowers** [comment] 2016-10-10 15:33
Duplicate of https://github.com/astralapp/astral/issues/80

Closing to keep the discussion in the other thread. Thanks for reporting.

**Closed by alexbowers** 2016-10-10 15:33 UTC
