### ISSUE TITLE
White screen after selecting tag which contains one or more dash/minus symbols

### ISSUE THREAD

**Issue by levytskiy** [astralapp/astral#77] opened 2016-08-24 12:06 UTC
Well, I am using dash/minus symbols to separate my tags. When selecting this tag the entire screen becomes white. Also, it is impossible to delete this tag.

My tags

![screen shot 2016-08-24 at 15 02 52](https://cloud.githubusercontent.com/assets/7404124/17929882/1f7b7a78-6a0c-11e6-9cf2-eb174d1819c3.png)

**Comment by syropian** [comment] 2016-09-20 17:53
This is because selecting a tag changes the url. I'm guessing it doesn't like an url thats just a bunch of dashes.

**Comment by levytskiy** [comment] 2016-09-23 10:13
@syropian I see, also it is impossible to delete such tag

**Comment by alexbowers** [comment] 2016-10-14 07:45
This is fixed in #105 because if it's empty we generate a random string for the slug

**Comment by syropian** [comment] 2016-11-12 17:07
Confirmed.

**Closed by syropian** 2016-11-12 17:07 UTC
