### ISSUE TITLE
can't search tag.....

### ISSUE THREAD

**Issue by vipheyue** [astralapp/astral#115] opened 2016-11-20 02:20 UTC
if this can **1.search tag and 2. notes .**
and show my notes this is best tool!!!

**Comment by vipheyue** [comment] 2016-11-20 02:21
show 3. my notes is very important

**Comment by syropian** [comment] 2016-11-20 02:26
Notes can be searched in the search bar

**Comment by vipheyue** [comment] 2016-11-20 02:34
yes  notes can searched .
i want two functions improve  user experience.
1. search tag 
2. show my notes in panel.

now.. if i want search my note ... i must write note .. can't search by tag 

tag show in panel i like ...this .. if note also show in panel it's very good

**Comment by syropian** [comment] 2016-11-20 02:36
Apologies, I'm not 100% what you mean. Do you mean you want to be able to filter your tags by a search query, or filter your stars by tags within the search bar?

**Comment by vipheyue** [comment] 2016-11-20 02:40
yes 

发自我的 iPhone

**Comment by vipheyue** [comment] 2016-11-20 02:42
search tag and dispaly my notes in home panel

发自我的 iPhone

**Comment by vipheyue** [comment] 2016-11-20 02:44
filter my tags by a search query

�������� iPhone

> �� 2016��11��20��������10:36��Collin Henderson <notifications@github.com> ������
> 
> filter your tags by a search query

**Comment by syropian** [comment] 2016-11-20 02:48
Filtering tags is a dupe of #9. 

I realize english is not your first language and the language barrier is making it a little tough to understand what you want with notes. It seems like you want notes to show without clicking a button or something, but unfortunately that would clutter the interface.

Closing for now.

**Closed by syropian** 2016-11-20 02:48 UTC
