### ISSUE TITLE
Refresh button - fetch new / current stars if something has changed (bypass cache)

### ISSUE THREAD

**Issue by DanielRuf** [astralapp/astral#109] opened 2016-11-07 11:07 UTC
The cache is currently set to 120 minutes https://github.com/astralapp/astral/blob/138074d181ba39d9bcc7dc302c7d88759e3a6872/app/Lib/GithubClient.php#L13

But when I add new stars on GitHub, they do not directly show up in Astral so we have to wait at least 120 minutes until we see the new stars in Astral. It would be helpful to show some info that the current stars in Astral are delivered from the cache and provide a refresh button to clear the cache and fetch the new stars.

**Comment by alexbowers** [comment] 2016-11-07 11:56
Duplicate of https://github.com/astralapp/astral/issues/88

We will track it in there.

Thanks for reporting, feel free to subscribe to that other issue to receive notifications when we have progress to report on it.

**Closed by alexbowers** 2016-11-07 11:56 UTC

**Comment by DanielRuf** [comment] 2016-11-07 12:16
@alexbowers thanks, unfortunately oversaw this issue.

**Comment by alexbowers** [comment] 2016-11-07 12:17
No problem :)

Happy to take duplicate reports rather than something get not reported at all.
